### PR TITLE
Add Worksheet.add_data_validation

### PR DESCRIPTION
**Pull request by danvk**
See https://openpyxl.readthedocs.io/en/stable/api/openpyxl.worksheet.worksheet.html?highlight=worksheet#openpyxl.worksheet.worksheet.Worksheet.add_data_validation

### CODE REVIEW

**Comment by MartinThoma** [comment]
@danvk CI is failing `openpyxl-stubs/worksheet/worksheet.pyi:116: error: Name "DataValidation" is not defined`

**Comment by danvk** [comment]
@MartinThoma added the missing import, we should be good now.

What threw me off was that `worksheet.pyi` already contained a referenced to `DataValidationList` without importing it:

https://github.com/MartinThoma/openpyxl-stubs/blob/b8bc5b5a0dae1d67a5455f5288fdf48bf7631965/openpyxl-stubs/worksheet/worksheet.pyi#L52

I see now that this is in implementation code, which I assume is ignored in `.pyi` file? Can it just be removed?

**Comment by MartinThoma** [comment]
Huh, intersting. Yes, I guess it could be removed.

Thank you for fixing it! And thank you for the PRs :heart:

**Comment by MartinThoma** [comment]
`0.1.25` was just released with this fix

**Pull request merged**
